### ISSUE TITLE
Very buggy when jumping to fresh parts of file

### ISSUE THREAD

**Issue by Amparose** [bicarlsen/vintage_relnums#2]
On ST4, the redraw of the line numbers is very flaky: some lines are empty, others get two columns of line numbers as it redraws, which happens slowly at times. This with a file of 2k lines.

<img width="282" alt="Screen Shot 2021-06-16 at 8 57 06 pm" src="https://user-images.githubusercontent.com/949192/122277021-b4bc3d00-cee5-11eb-9c06-f801f820ec46.png">
<img width="215" alt="Screen Shot 2021-06-16 at 8 57 27 pm" src="https://user-images.githubusercontent.com/949192/122277026-b5ed6a00-cee5-11eb-84a4-06b12e70fcaf.png">

**Comment by bicarlsen** [comment]
Thanks for the interest @Amparose. I haven't updated this to ST4 yet, but I will play with it in the next days to see if I can get it working well, then submit it to Package Control as you suggested.

**Comment by bicarlsen** [comment]
I believe this issue has been resolved with the latest push. Can you give it a try and let me know if it seems better?

**Comment by Amparose** [comment]
This works better however there are some aesthetic issues:

<img width="168" alt="image" src="https://user-images.githubusercontent.com/949192/122622761-0ad1e180-d09a-11eb-9b29-636a348aed82.png">

- Uses its own font, which isn't mono-space.
- Because of the above, the alignment of editor rows is uneven and jumps around between the single and multiple digit line numbers.
- Needs more padding between it and the content.

I'd also like a command to be able to toggle relnums on/off.

**Comment by bicarlsen** [comment]
> This works better however there are some aesthetic issues:
> 
> <img alt="image" width="168" src="https://user-images.githubusercontent.com/949192/122622761-0ad1e180-d09a-11eb-9b29-636a348aed82.png">
> 
> * Uses its own font, which isn't mono-space.
> * Because of the above, the alignment of editor rows is uneven and jumps around between the single and multiple digit line numbers.
> * Needs more padding between it and the content.
> 
> I'd also like a command to be able to toggle relnums on/off.

Thank you so much for the funtctionality input. I really appreciate it.

I have moved the settings into a `sublime-settings` file, so they are now customizable. I have also added a `font_face` and `padding` setting to address the two points you brought up.

**Comment by Amparose** [comment]
Awesome! You added colour codes too, which is great.

Hmm it seemed fixed but when I opened the vintage_relnums.py to see if there was any command to toggle on/off, the jumpy/refresh bug came back:

https://user-images.githubusercontent.com/949192/122636568-3ed4f300-d0ea-11eb-9d8d-17ef3bee2e99.mp4

Doesn't seem to happen in all file types and file length doesn't seem to be the trigger.

**Comment by bicarlsen** [comment]
I just made some major changes to the package. I suggest re-reading the README, and chekcing it out.

Thanks again for all your feedback, this has been quite a nice project to work on.

**Comment by bicarlsen** [comment]
@Amparose Let me know if you get a chance to try the new features and if you have any other feedback, otheriwse I'll close this issue.

**Comment by Amparose** [comment]
Unfortunately, the jumpy bug is still there, at least when viewing python files.
